### ISSUE TITLE
Copying std::function into sol::state throws "memory allocation error: block too big" (regression v3.2.1 to v3.2.2, clang only)

### ISSUE THREAD

**Issue by lubgr** [ThePhD/sol2#1067] opened 2020-11-16 12:58 UTC
Consider this snippet,
```c++
#include <sol/sol.hpp>
#include <functional>

int main(int, char **)
{
    sol::state lua;

    lua.open_libraries(sol::lib::base);
    lua["fct"] = std::function<int()>{[](){ return 42; }};
    lua.script("print(fct())");

    return 0;
}
```
Under certain circumstances (see below) this gives me
```
[sol3] An error occurred and panic has been invoked: memory allocation error: block too big
libc++abi.dylib: terminating with uncaught exception of type sol::error: lua: error: memory allocation error: block too big
```
What could be the issue? I tested with the following setup
| Compiler | sol version | lua version | Result |
| :-------- | :---------- | :----------- | :----- |
| gcc 10    |  v3.2.2       | 5.4.1, 3.5.5   | Ok      |
| gcc 10    | v3.2.1         | 5.4.1, 3.5.5   | Ok      |
| clang 11  | v3.2.2         | 5.4.1, 3.5.5  | Throws  |
| clang 11  | v3.2.1         | 5.4.1, 3.5.5  | Ok  |

This is on MacOS Catalina, with the standard Apple clang, version 11.0.3. What could be the issue? Let me know if you need any further info.

**Comment by ThePhD** [comment] 2020-11-16 14:58
I don't have a mac to test on, so I'm just gonna pray this can repro under Clang on Windows...

**Comment by lubgr** [comment] 2020-11-16 15:06
Thanks for giving it a try. You can also give me some hints where I should take a closer look.

**Comment by lubgr** [comment] 2020-11-16 23:17
I did a `git bisect` (less automated than that sounds, though). The commit that introduces the issue is 63df43e061ea35902897b17def0867c70311fc1d. The diff is somewhat `clang-format`-heavy, I hope that helps anyhow?

**Comment by lubgr** [comment] 2020-11-17 09:59
[Here](https://gist.github.com/lubgr/9e89206be4aad240ba932eb5af312601) is the stacktrace.

**Comment by ThePhD** [comment] 2020-11-19 02:22
> frame #15: 0x00000001000127a3 stdfct`lua_newuserdatauv(L=0x0000000101008208, size=18446603340788801952, nuvalue=1) at lapi.c:1315:7

That value is too large to be represented in a 64-bit unsigned integer, and comes out to be `-140,732,920,749,664`, signed.

Chances are, there's some bad math happening here that I'm not accounting for? I can't reproduce but I can check things over very carefully to make sure I'm not making a bad assumption.

**Comment by ThePhD** [comment] 2020-11-19 21:43
This should be fixed in latest.

**Closed** 2020-11-19 21:42 UTC
Labels: Maybe.Bug...?

**Comment by ThePhD** [comment] 2020-11-19 21:44
(That is, I built with Clang 11 of that exact version with Lua 5.4.1, x86 and x64, and did both tests and it was okay. It's also part of the test suite now so I can track this.)

**Comment by velkyel** [comment] 2020-12-07 15:10
no, it is not still correctly fixed.
(my setup: sol v3.2.2., lua 5.4.2, code running on iOS)
