### ISSUE TITLE
demangle fails on macOS

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#149] opened 2016-07-25 16:55 UTC
The call to `abi::__cxa_demangle` fails and returns a `NULL` pointer. 

## Problem function

```C++
#ifndef SOL_NO_RTTI
#if defined(__clang__)
		inline std::string get_type_name(const std::type_info& id) {
			int status;
			char* unmangled = abi::__cxa_demangle(id.name(), 0, 0, &status); // NULL 
			std::string realname = unmangled;
			std::free(unmangled);
			return realname;
		}
#elif defined(__GNUC__)
		inline std::string get_type_name(const std::type_info& id) {
			int status;
			char* unmangled = abi::__cxa_demangle(id.name(), 0, 0, &status);
			std::string realname = unmangled;
			std::free(unmangled);
			return realname;
		}
#endif // g++ || clang++
#endif // No RTII
#else
#error Compiler not supported for demangling
#endif // compilers
```

## Error Trace

```
#1	0x00000001003c1485 in std::__1::char_traits<char>::length(char const*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:640
#2	0x00000001005816e1 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(char const*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:2005
#3	0x00000001005816a0 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(char const*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:2003
#4	0x0000000100581694 in sol::detail::get_type_name(std::type_info const&) at /Users/kevin/dev/procsim/build-xcode/include/sol.hpp:4104
#5	0x00000001005f3736 in _ZN3sol6detail13demangle_onceINS_15function_detail16functor_functionIN12_GLOBAL__N_19encode_fnILN7procsim4conf8Encoding14UnderlyingTypeEn8EEEEEEENSt3__112basic_stringIcNSC_11char_traitsIcEENSC_9allocatorIcEEEEv at /Users/kevin/dev/procsim/build-xcode/include/sol.hpp:4125
#6	0x00000001005e72d1 in _ZN3sol6detail8demangleINS_15function_detail16functor_functionIN12_GLOBAL__N_19encode_fnILN7procsim4conf8Encoding14UnderlyingTypeEn8EEEEEEENSt3__112basic_stringIcNSC_11char_traitsIcEENSC_9allocatorIcEEEEv at /Users/kevin/dev/procsim/build-xcode/include/sol.hpp:4144
#7	0x00000001006003a5 in ::__cxx_global_var_init.54() at /Users/kevin/dev/procsim/build-xcode/include/sol.hpp:4179
#8	0x00007fff5fc1310b in ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) ()
#9	0x00007fff5fc13284 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) ()
#10	0x00007fff5fc0f8bd in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#11	0x00007fff5fc0f852 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#12	0x00007fff5fc0f743 in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) ()
#13	0x00007fff5fc0f9b3 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) ()
#14	0x00007fff5fc020f1 in dyld::initializeMainExecutable() ()
#15	0x00007fff5fc05d98 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#16	0x00007fff5fc01276 in dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) ()
#17	0x00007fff5fc01036 in _dyld_start ()
```

The problem is occurring because `id.name()` is apparently an invalid type. 
I looked at `id` and the returned status:
 
```
name: N3sol15function_detail16functor_functionIN12_GLOBAL__N_19encode_fnILN7procsim4conf8Encoding14UnderlyingTypeEn8EEEEE
status: -2
```

Type signature for "function" in question:

```c++

namespace { // annonymous
template <Encoding::UnderlyingType type> 
// Encoding::UnderlyingType is an enum class for int8_t
struct encode_fn {
  void operator()(const sol::object obj) {}
};
}
```

Usage:

```C++
lua->set_function("i8", encode_fn<Encoding::UnderlyingType::i8>()); // i8 = -8
```

I think this bug is actually an LLVM bug, which is always fun.

**Comment by Nava2** [comment] 2016-07-25 17:00
So, I changed the `encode_fn` signature to not use a template, and the error goes away. 

I'm fairly confident now that this is a bug with macOS version of clang.

**Comment by Nava2** [comment] 2016-07-25 17:12
Further investigation found the real bug: clang can not demangle templates that use `enum class` values that are negative. This fails:

```c++
enum class test_enum: int8_t {
    under_0 = -1,
    zero = 0
};

template <test_enum T>
struct test {
    
};

int main()
{
    {
        const auto& info = typeid(test<test_enum::zero>);
        int status;
        char* name = abi::__cxa_demangle(info.name(), 0, 0, &status);
        std::cout << "name = " << name << " status = " << status << std::endl; // name = test<(test_enum)0> status = 0
        std::free(name);
    }
    {
        const auto& info = typeid(test<test_enum::under_0>);
        int status;
        char* name = abi::__cxa_demangle(info.name(), 0, 0, &status); // name == NULL
        std::cout << "name = " << name << " status = " << status << std::endl; // segfault
        std::free(name);
    }

    return 0;
}

```

**Comment by ThePhD** [comment] 2016-07-25 17:38
Well, at least we now know VC++ isn't the only compiler that likes to derp out.

Since it's not something explicitly in my control, the most I can do is file a bug for this on LLVM and call someone's attention to it. I still have to update travis-ci to see if the old old old apple-clang compiler bug related to tuples has gone away as well...

But that also requires fighting with Travis-CI and maybe introducing Docker to get a more up-to-date VM to work with. Which is asking a lot for one compiler that keeps introducing regressions in the original clang codebase.

**Comment by Nava2** [comment] 2016-07-25 18:03
I opened a bug with Apple's tracker. The test passed fine on clang3.7, so it's probably just Apple being delayed with releases. I am currently downloading Xcode8 to see if it works with the beta.

**Comment by Nava2** [comment] 2016-07-25 18:04
Oh, only thing that could be done on the `sol2` end would be to add an assert + message for when the status is not `0`. Currently, it just tries to progress without checking, which is probably bad.

**Comment by ThePhD** [comment] 2016-07-25 18:07
Oh, dear, I just noticed that too. I thought I merged the branch that did that work from Peter Hadju as far back as sol 1.0 from Rapptz/sol...

Oops.

Also, one way we could avoid this entirely is to get a REALLY good, consistent way of parsing __PRETTY_FUNCTION__ and the VC++ equivalent, so that we would not need to take the dependency on `typeid` or `typeinfo` at all and not have to do the demangling that way.

**Comment by Nava2** [comment] 2016-07-25 18:16
On GCC and Clang, `__PRETTY_FUNCTION__` might work, but it becomes harder to make sure that's called in the right place. 

That `abi` call is kind of rough, but does MSVC not provide something similar for getting the unmangled name?

**Comment by ThePhD** [comment] 2016-07-25 18:27
MSVC's `typeinfo` provides a demangled name from the `.name()` function right off the bat. IIRC it also comes fully qualified, too.

`__FUNCDSIG__` (or just `__FUNC__` or whatever) in VC++ is similar to `__PRETTY_FUNCTION__`. Calling it at the right place is just a matter of nesting it within a specific function call, finding the name of that function, and then parsing the data out from there.

We already do this in part right now when someone turns of RTTI: I turn `__PRETTY_FUNCTION__` and `__FUNCDSIG__` into strings and then apply some rudimentary "find these characters, do stuff with it". It's by no means bulletproof, however, which is why I haven't made the full switch to it from just relying on the RTTI names.

**Comment by Nava2** [comment] 2016-07-25 21:32
Oh, and I checked if this code works on Xcode8 and clang-3.7+, it fails on Xcode, passes on 3.7. Fun. 👍

**Comment by ThePhD** [comment] 2016-07-26 13:15
Yeah... I'll work on switching everything to parsing `__FUNCDSIG__` AND `__PRETTY_FUNCTION__`. It will be more reliable across exceptions / no-exceptions and should eliminate this bug. It will still take me a while, though, because figure out if things change between versions of compilers and stuff is going to be.... rough.

**Comment by ThePhD** [comment] 2016-07-29 05:18
On the To-Do list for later, since I'm tired.

**Closed** 2016-08-07 16:41 UTC
Labels: Feature.CanDo, Maybe.Later

**Comment by ThePhD** [comment] 2016-08-07 17:01
Hey. Took me a while and a bunch of parsing, but you should no longer encounter `cxxabi` issues or `typeid` issues because we no longer use it for demangling since [this commit](https://github.com/ThePhD/sol2/commit/9c67e9310e9aa37a5d836c9fe6da527f1dfb3a4c).

It took a bit of work, but we now also have [tests to make sure you for basic cases that you'll be covered](https://github.com/ThePhD/sol2/commit/ba5465dd8697277ba5126afb25b0471e0ae33527#diff-92ef606830d7ce2f6e16a861e46d8e6aR86). Note that relying on this kind of demangling is tricky, as it's implementation-defined behavior and clang/gcc can give us a giant middle finger whenever it so damn pleases, but... well, I guess that's the nature of the beast.
