### ISSUE TITLE
Crashing when trying to destory a lua state with an existing usertype

### ISSUE THREAD

**Issue by an0nym0us69** [ThePhD/sol2#490] opened 2017-08-20 14:53 UTC
Hello,

i've started getting crashes when destroying a lua state which have an existing usertype on the state 
example : 
`local vec = Vector(0,0,0)`

sorry, i don't really know when it started but i might be able to give you a timeframe and sorry for no debug atachement cause i didn't have enough time to test, but i'm certain the issue is something about destroying the usertypes...
http://i.imgur.com/VNxoPpj.png
^ probably from these updates, since the "update single, prepare for tests" is working pretty fine here..

**Comment by Nava2** [comment] 2017-08-20 14:55
@an0nym0us69 you could figure out exactly which commit by using: [`git bisect`](https://git-scm.com/docs/git-bisect).

If you'd rather not, could you provide a full working example showing the bug?

**Comment by Nava2** [comment] 2017-08-20 14:56
Also, I think this may be a dupe of #489.

**Comment by an0nym0us69** [comment] 2017-08-20 15:00
^ this might be the same issue, it fails to deallocate the usertypes i think yeah.., the lua state destruction works fine until i put a usertype instance inside the state

**Comment by OrfeasZ** [comment] 2017-08-21 05:24
@an0nym0us69 if you can provide an example to reproduce this issue I'm sure it would be very helpful in tracking it down. My codebase is rather large, so I haven't been able to isolate one myself yet.

**Comment by ThePhD** [comment] 2017-08-21 19:44
Fixed.

**Closed by ThePhD** 2017-08-21 19:44 UTC
Labels: Duplicate
