### ISSUE TITLE
Crash when writing to readonly properties

### ISSUE THREAD

**Issue by jcxz** [ThePhD/sol2#1087] opened 2020-12-10 17:18 UTC
The following code causes a crash in Visual Studio 2019 when compiling in release mode:

```
#define SOL_NO_EXCEPTIONS 1  // commenting this out will stop the crash
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>
#include <iostream>

struct MyStruct
{
    int prop = 10;
};

int main()
{
    std::cerr << "================= script crash test ===================" << std::endl;

    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::package, sol::lib::coroutine, sol::lib::string, sol::lib::os, sol::lib::math, sol::lib::table, sol::lib::io, sol::lib::debug);
    lua.new_usertype<MyStruct>("MyStruct", "prop", sol::readonly_property(&MyStruct::prop));
    lua.safe_script("local s = MyStruct.new(); s.prop = 20", sol::script_pass_on_error);

    std::cerr << "================= THE END ===================" << std::endl;

    return 0;
}
```

The key here is that `SOL_NO_EXCEPTIONS` has to be defined, when `SOL_NO_EXCEPTIONS` is defined, the Lua script in the code above will crash the program instead of passing on the error.

I am thinking, how good of an idea is it actually to define `SOL_NO_EXCEPTIONS` ?

Reading through sol's sources, I found this comment for example:
```
// Lol, what do you want, an error printout? :3c
// There's no sane default here. The right way would be C-style abort(), and that's not acceptable, so
// hopefully someone will register their own stack_fail thing for the `fx` parameter of stack_guard.
```
which makes me think, that maybe `SOL_NO_EXCEPTIONS` is not well defined in all cases and thus is not such a good idea to turn on ...

**Comment by ThePhD** [comment] 2020-12-16 20:23
The comment there is a playful one, but it captures the idea: there's no way I can help you at that point. You're in panic territory when that call fails because writing to it is a failure. I just have to call `lua_error` and hope for the best.

That being said, this should _still_ work, exceptions or not. There's probably something I'm messing up, here!

**Comment by ThePhD** [comment] 2020-12-18 04:37
This is fixed now in latest and is part of the regression tests.

Thanks!

**Closed by ThePhD** 2020-12-18 04:37 UTC
