### ISSUE TITLE
Registering usertype function issues: "is_noexcept': undeclared identifier,'traits_type' is not class...

### ISSUE THREAD

**Issue by TwinHits** [ThePhD/sol2#1021] opened 2020-08-30 14:39 UTC
Hello! 

I am having issues registering a new user type's functions. I am getting

```
'is_noexcept': undeclared identifier	
'traits_type': is not a class or namespace name
expression did not evaluate to a constant 
```
from function_types_stateless.hpp	173	

on all four of these registration strategies: 

```
this->luaState.set_function("moveRight", &TIEntityScriptInterface::moveRight);
```

```
this->luaState.new_usertype<TIEntityScriptInterface>("tientity", sol::no_constructor,
	"moveRight", &TIEntityScriptInterface::moveRight);
```

```
sol::usertype<TIEntityScriptInterface> interface_type = this->luaState.new_usertype<TIEntityScriptInterface>("tientity", "moveRight", &TIEntityScriptInterface::moveRight);
```

```
sol::usertype<TIEntityScriptInterface> interface_type = this->luaState.new_usertype<TIEntityScriptInterface>("tientity");
interface_type["moveRight"] = &TIEntityScriptInterface::moveRight; // Issue occurs when this line is introduced
```

Am I missing something from the documentation? (https://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html)

I'm on Windows 10, Visual Studio 2019, C++17, and I'm using sol v3.2.1.

Thank you!

For additional code, here's my TIEntityScriptInterface class:
```
class TIEntityScriptInterface {
    public:
        TIEntityScriptInterface(TIEntity&);
        ~TIEntityScriptInterface() {};

        void moveRight();
...

    private:
        TIEntity* tientity = nullptr;
};
```
```
void TIEntityScriptInterface::moveRight() {
    MovesComponent* movesComponent = this->tientity->getComponent<MovesComponent>();
    SpriteComponent* spriteComponent = this->tientity->getComponent<SpriteComponent>();
    if (movesComponent != nullptr) {
        MovesComponentSystem::Instance()->setTargetPosition(*movesComponent, *spriteComponent, Direction::RIGHT);
    }
}
...
```

```

**Comment by ThePhD** [comment] 2020-08-30 15:51
Duplicate of: https://github.com/ThePhD/sol2/issues/1008

This is an MSVC compiler bug. I am unfortunately in the middle of doing schoolwork, establishing a routine, fixing up sol2's undefined behavior uses, and implementing #embed in Clang and GCC so I can defend it on... wow I have to defend that paper THIS COMING WEDNESDAY to the committee yaaaay

I will get to this, or pray that MSVC fixes their compiler. Whichever happens first.

There are some quick fixes at the bottom of the other issue. I will post here if I get a fix that makes MSVC stop crapping its pants.

**Closed** 2020-08-30 15:51 UTC
Labels: Duplicate

**Comment by TwinHits** [comment] 2020-08-30 18:42
Thank you so much! Good luck with your paper, and thank you for this wonderful library :).
