### ISSUE TITLE
possible issues of std::vector on pointers

### ISSUE THREAD

**Issue by an0nym0us69** [ThePhD/sol2#491] opened 2017-08-20 14:58 UTC
hello again,

i have an std::vector<player*> on my C++ side, it always worked fine, and still does, the size i got was correct, the array was also fine, yet on my lua code, when i try to loop and do any call, the pointer to the player is wrong (and it's not a nullptr lol...)
http://i.imgur.com/SqLTh6v.png

here is the list of pointers in that vector :

http://i.imgur.com/ZWt2S8p.png

all i'm doing on my lua is a loop and a call to 1 function.

**Comment by Nava2** [comment] 2017-08-20 15:37
Can you post the code? It's not possible to debug your situation with the information you've provided. Are you indexing into your table in Lua based on 0 or 1?

**Comment by ThePhD** [comment] 2017-08-20 15:53
I second @Nava2 . I don't see any code. Not even a reproducible example of any kind. Just a bare screenshot of pointers and that an exception happened.

**Comment by an0nym0us69** [comment] 2017-08-20 16:45
okay.. well my explanation was really vague..
it was a function in C++, but it's rather a property, and i exported it to lua as property.
this is how i am accessing it in lua : 
`for index, player in pairs(ObjectManager.Heroes) do
    if player.isValid then -- <= this one crashes because of access violation, i was just reading this->0x4, turned out this is 0x2 (and some random addresses sometimes, it just doesn't return the right pointer)
    ----
`

**Comment by Nava2** [comment] 2017-08-20 16:47
Is `isValid` part of `Player`? If so, it should be `player:isValid`. Otherwise, I'm out of ideas.

**Comment by an0nym0us69** [comment] 2017-08-20 16:47
yes it is part of player, but it's a property so it shouldn't be player:isValid.

**Comment by ThePhD** [comment] 2017-08-20 18:18
Okay, well. I tried this on my personal develop branch and it seems fine, so maybe I just need to push all the changes I've made and your problem goes away.

Note that `pairs` doesn't work in Lua 5.1 / LuaJIT no matter what you do.

If the code below is not reflective of what you're trying to do, please let me know.

````
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

int main(int argc, char* argv[]) {

	// setup shims / mocks of problem
	struct Player {
		bool is_valid() const {
			return true;
		}
	};

	struct ObjectManager {
		Player p1;
		Player p2;

		std::vector<const Player*> heroes() {
			const Player* pp1 = &p1;
			const Player* pp2 = &p2;
			return std::vector<const Player*>{ pp1, pp2 };
		}
	};

	// setup example
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<Player>("player",
		sol::default_constructor,
		"isValid", sol::readonly_property(&Player::is_valid)
	);
	lua.new_usertype<ObjectManager>("objectManager",
		sol::default_constructor,
		"Heroes", sol::readonly_property(&ObjectManager::heroes)
	);

	lua["ObjectManager"] = ObjectManager{};

	const std::string code = R"(
	for index, player in pairs(ObjectManager.Heroes) do
		if player.isValid then -- <= crash
			print("totes valid ( ^-^)b ")
		else
			print("not valid: P A N I C \\ ( O.O)/")
		end
	end
)";

	// demonstrate problem:
	try {
		lua.safe_script(code);
	}
	catch (const sol::error& err) {
		std::cerr << "you dun goofed:\n\t" << err.what() << std::endl;
	}

	return 0;
}
````

Output:
![works for me](http://i.imgur.com/dJgTG6n.png)

**Comment by EloSuite** [comment] 2017-08-20 18:29
i'm using lua 5.3.4 as an engine, and well i don't really have any problem with the .isValid, the only thing that bothers me is that random pointer that comes out of nowhere and doesn't exist on the std::vector at all, it happens randomly, note that my loop through those players isn't stopping at all, let's hope it will get fixed on next update then 🙌 
anyways thanks for all the work you put into the project 👍

**Comment by an0nym0us69** [comment] 2017-08-20 18:31
i'm using lua 5.3.4 as an engine, and well i don't really have any problem with the .isValid, the only thing that bothers me is that random pointer that comes out of nowhere and doesn't exist on the std::vector at all, it happens randomly, note that my loop through those players isn't stopping at all, let's hope it will get fixed on next update then 🙌 
anyways thanks for all the work you put into the project 👍

**Comment by ThePhD** [comment] 2017-08-21 19:43
This issue should be fixed now.

**Closed by ThePhD** 2017-08-21 19:43 UTC
Labels: Help.Desk, Maybe.Bug...?, No.Repro
