### ISSUE TITLE
Compilation error after upgrading to VS2019 16.7

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#1008] opened 2020-08-08 17:11 UTC
I just upgraded VS2019 from version 16.6, to 16.7, now this code causes sol to explode... 🤯 

```cpp
	sol::table metatable;
	metatable[sol::meta_function::new_index] = sol::as_function([](sol::table table, const char* name, sol::object object){});
```

`1>...\sol\function_types_stateless.hpp(38,1): error C2653: 'traits_type': is not a class or namespace name`

Using latest master commit of sol.

**Comment by SirLynix** [comment] 2020-08-08 18:33
I have the same issue with Sol 3.2.1

**Comment by alitteneker-ucla** [comment] 2020-08-09 07:30
I have the same issue, and I can confirm it appears with both x86 and x64 configurations both with and without conformance mode. It might have something to do with [this visual studio conformance change](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#unnamed-classes-in-typedef-declarations), but I would've thought disabling conformance mode would have cleared the error.

From looking at the sol source, MSVC is basically just ignoring some earlier typedefs, which frankly seems beyond nuts. Even weirder, I haven't been able to find any recent issues in the Microsoft Developer Community that I would have thought would have surely resulted from an issue like literally ignoring typedefs. Anyone have any idea what's going on here?

**Comment by alitteneker** [comment] 2020-08-09 07:32
I have the same issue, and I can confirm it appears with both x86 and x64 configurations both with and without conformance mode. It might have something to do with [this visual studio conformance change](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#unnamed-classes-in-typedef-declarations), but I would've thought disabling conformance mode would have cleared the error.

From looking at the sol source, MSVC is basically just ignoring some earlier typedefs, which frankly seems beyond nuts. Even weirder, I haven't been able to find any recent issues in the Microsoft Developer Community that I would have thought would have surely resulted from an issue like literally ignoring typedefs. Anyone have any idea what's going on here?

**Comment by ThePhD** [comment] 2020-08-09 07:38
The error seems to come from "You're Templating Too Hard".

This is giving me Visual Studio November 2013 CTP PTSD, all over again...

Well. The code related to all this is due a rewrite: some simplifications might save us from the error anyways?

**Comment by alitteneker** [comment] 2020-08-10 03:43
@ThePhD You very well might be right that the root cause is some new MSVC template ridiculousness, but I wasn't able to replicate the issue in a fresh sol-free project.

To throw a wrench into things, I just tried out the latest VS2019 preview (16.8 preview 1), which does **not** display the `'traits_type': is not a class or namespace name` error. It might be that the next minor VS2019 minor release (16.7.1) will fix the issue, but we won't know for a week or two.

**Comment by brunolapastina** [comment] 2020-08-10 17:11
I'm pissed off that I updated to 16.7 a couple hours before seeing this issue.
Anyway... I found a workaround that might help other.

I`m using the single include file and got the error at:
`1>sol2-develop\single\include\sol\sol.hpp(17459,1): error C2653: 'traits_type': is not a class or namespace name
`

As a workaround, I noticed that if I comment the conditional noexcept, the compilation works. Like this:
`static int real_call(lua_State* L) /*noexcept(traits_type::is_noexcept)*/ {`

I know this is not ideal, but at least it allows me to keep working on my code while Microsoft doesn't release an update (or I hit another problem)

**Comment by sagamusix** [comment] 2020-08-10 19:55
Tangentially related: @ThePhD If you haven't done so already, you may want to ask some MSVC folks if they can include sol in their internal real-world test cases. When we were in contact with them regarding an ICE on our own code some years ago, we asked them if it would be possible to do so because we managed to break their compiler (and to be fair, also the other big C++ compilers) with our code rather frequently. They agreed that it would be a good idea and said that as a first step, we should get our code into vcpkg. I see that sol is already on vcpkg so maybe you can give them a shout at visualcpp@microsoft.com. This should help them finding regressions or ICEs.

**Comment by brunolapastina** [comment] 2020-08-11 20:40
Just updated to 16.7.1 and the problem got fixed.
The original code is compiling again.

**Comment by sagamusix** [comment] 2020-08-11 20:45
Thanks, I'll update to confirm. Problem right now is that the Visual Studio Installer has to be updated and it's downloading at 150KB/s... 😭

**Comment by sagamusix** [comment] 2020-08-11 21:07
Unfortunately it still seems to be broken here with 16.7.1. `/permissive-` or not doesn't make a difference.

**Comment by alitteneker** [comment] 2020-08-11 21:09
Unfortunately, it's still broken with 16.7.1 for me as well.
@brunolapastina Did you do anything extra after updating, like start a new project or change project settings?

**Comment by brunolapastina** [comment] 2020-08-11 21:28
Ow no! I prematurely posted 😳 
I just recompiled my previous solution, without noticing that I had commented some things and one of them was the line that triggered the problem.

You are absolutly right @sagamusix and @alitteneker. The problem persists on 16.7.1
At least commenting the conditional noexcept still works.

**Comment by hsdk123** [comment] 2020-08-11 23:34
I'm also seeing this, would be great to get a fix.

**Comment by tobyplowy** [comment] 2020-08-14 18:24
My team is currently also facing this issue on MSVC 16.7.1.

**Comment by sagamusix** [comment] 2020-08-14 18:26
Please avoid adding "me too" comments. They just add noise to the discussion and are not helpful to fixing this issue.

**Comment by tkozybski** [comment] 2020-08-15 09:20
Workaround for those that want the code to compile but doesn't want to edit sol2 source.

In Visual Studio installer, click modify on the Visual Studio 2019, go to "Individual Components", search and download  "MSVC v142 - VS 2019 C++ build tools (v14.26)" for your architecture, then in your projects properties go to Advanced and select "14.26.28801" in the "MSVC Toolset Version".

It'll use the working compiler version until the proper fix is released.

**Comment by Ung0d** [comment] 2020-08-19 09:27
Seems like 16.7.2 update still doesn't contain the fix from the preview..
Can someone confirm?

**Comment by ThePhD** [comment] 2020-08-26 17:01
Still busted for me, yeah.

I'm doing a lot but this one's on my radar still. I'm trying not to just say "well lol no more `noexcept` I guess xD!".

But I just might have to...

**Comment by DomRe** [comment] 2020-08-31 05:59
Im running this on MSVC 16.8 preview 2 and it compiles. Seems it might have been fixed with 16.8?

**Comment by sagamusix** [comment] 2020-08-31 09:17
Yes, this has been [asserted before](https://github.com/ThePhD/sol2/issues/1008#issuecomment-671149909); it seems like we might "just" need to wait for 16.8 to go gold and then we can have our `noexcept` again.

**Comment by ThePhD** [comment] 2020-09-05 21:29
This is fixed in latest. "Fixed", as in, I just turned off noexcept-ness for MSVC.

**Closed by ThePhD** 2020-09-05 21:29 UTC

**Comment by sagamusix** [comment] 2020-11-13 18:05
16.8 is now officially now, maybe it's time to revisit this code :)

**Comment by alitteneker** [comment] 2020-11-13 21:32
I can confirm that Visual Studio 16.8.1 is now compiling successfully with the original sol 3.2.0 and 2.20.6, just in case anyone was missing the ol' noexcepts. Annoyingly, nothing in the release notes for the new MSVC versions seems like an obvious culprit for these issues.
