### ISSUE TITLE
Testing on OSX

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#24] opened 2016-03-02 06:20 UTC
I'll investigate this one, just want a record of it. 

Known failures: 

* [x] xcode7 appleclang, lua53
* [x] gcc-5, luajit51

[Build 1](https://travis-ci.org/Nava2/sol2/builds/113047289)

**Comment by Nava2** [comment] 2016-03-02 06:23
Third commit to silence the failure was the charm.

**Comment by ThePhD** [comment] 2016-03-03 15:11
If you want to fix this, you'll need to get a step-through debugger (or gdb if you're a Real Individual™) and go to tests.cpp on line 671 for the REQUIRE clause. However, the actual function call is earlier at 667. You'll need to step through that, and the 2 functions after those, to get an idea of why it's actually failing.

I unfortunately do not own a Macbook and have 0 plans on spending real money to get one.

````
-------------------------------------------------------------------------------
functions/deducing-return-order-and-multi-get
-------------------------------------------------------------------------------
tests.cpp:651
...............................................................................
tests.cpp:673: FAILED:
  REQUIRE( tcpp == triple )
with expansion:
  { 10, 0, 0 } == { 10, 11, 12 }
````

**Comment by Nava2** [comment] 2016-03-03 15:15
Yup, I'll look into it, thanks for the starting point. I have a macbook and love it. 

Using [Vagrant](http://vagrantup.com), there is an [osx box](https://github.com/AndrewDryga/vagrant-box-osx). I might look into that for my work, too. I have a minimal Vagrantfile written for my work (has some Qt stuff installing) that wouldn't be necessary for `sol2`, but I could port it if that's useful. It would give you a consistent linux and osx environment to work with for testing.

**Comment by ThePhD** [comment] 2016-03-03 16:14
You don't have to work TOO hard on this, now! I do have some minimal vagrant experience so I could do that. I also have a few friends with Macbooks so I could totally ask them to help too. Though I appreciate the help, most certainly :+1:!

**Comment by Nava2** [comment] 2016-03-03 16:29
It kind of falls into a "requirement" and I like working on FOSS stuff. It's more interesting than some of the other things I work on (like course work or marking).

**Comment by Nava2** [comment] 2016-03-03 16:35
This [Vagrantfile](https://gist.github.com/Nava2/b50a8bc34f6f06a2fabf) would be a good start for Linux parts. There's three configs: `gcc49`, `gcc5`, and `clang36`.

**Comment by ThePhD** [comment] 2016-03-29 17:32
Confirmed fixed gcc5 luajit51. Now it's just appleclang lua53.

**Comment by Nava2** [comment] 2016-03-29 17:38
Oh nice! I'm sorry, I've been so busy with course work I couldn't work on this. :-1:

**Comment by ThePhD** [comment] 2016-03-31 14:52
Looking into this on a vagrant box, it looks like this is an Appleclang failure, not our failure.

**Comment by Nava2** [comment] 2016-03-31 14:53
That's always promising.

**Comment by ThePhD** [comment] 2016-03-31 15:08
Plowing through this with lldb, it very much looks like clang is doing something wonky with its tuples. I'm almost confident this is a failure in appleclang now. I don't know how to proceed from here: I could be wrong, since I usually use gdb or the visual debugger of visual studio...

**Comment by ThePhD** [comment] 2016-03-31 15:21
I guess I close this ass "Can't Fix". Hopefully someone else might be able to pinpoint it better than I can in the future...

**Closed by ThePhD** 2016-03-31 15:21 UTC
Labels: Maybe.Bug...?

**Comment by Nava2** [comment] 2016-03-31 15:34
Relevant? https://llvm.org/bugs/show_bug.cgi?id=24779
