### ISSUE TITLE
LuaJIT 5.1: Exceptions are not rethrown through sol::error

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#28] opened 2016-03-03 05:26 UTC
In my code, I'm trying to force some sandboxing, one part of this is setting the `require` function to `nil`.

To test this, I create an "library script":
```lua
local M = {}
function M.foo()
    return "foo"
end
return M
```

I store this into a file in the test dir, `m.lua`, and then load it via:

```lua
local M= require('m')
assert(M.foo() == "foo");
```

On Lua 5.2, this throws a sol::error claiming the `require` function is `nil`. This is the expected behaviour, however, luajit exceptions are never caught and it throws an error unrecognized.

**Comment by Nava2** [comment] 2016-03-03 05:59
With a bit more testing, it seems to actually segfault the entire thread, which is odd. 

What's happening is that it is throwing `...` and `sol` isn't catching that ([source](http://luajit.org/extensions.html#exceptions)). There's a few options here: 

1. Use LuaJIT's C API to catch the exceptions ([link](http://luajit.org/ext_c_api.html))
  * Since this is a one-time overhead turn on/off, perhaps, if on LuaJIT, create a function to accept the function? Just thinking out loud
2. Accept that this is how LuaJIT works vs. Lua and ignore it :-1:

**Comment by ThePhD** [comment] 2016-03-03 07:35
We do (1) already in the [latest](https://github.com/ThePhD/sol2/commit/e06b939d73a0b1a6f2a18c2c8eff546373b4fdf6). The only place we actually throw a `sol::error` is during the `atpanic` function. If luajit is failing internally and not properly calling it there's really not anything we can do.

**Comment by ThePhD** [comment] 2016-03-03 07:54
It.. seems to work properly, but I'm using Windows x64. I assume it works properly on other x64-platforms. Support for exceptions, as the tables on the page for extensions/exceptions displays, depends on your platform. I have made it so every function bound through `sol` has an exception-catching trampoline placed under it that will translate things to a lua error. `protected_function` also goes to great lengths to ensure that exceptions are caught (as best as they can be through the lua code) and then translated into lua errors onto the stack (which also get filtered by a handler function, if there is one).

The exception wrapping can be turned off with SOL_NO_EXCEPTIONS being defined, but I only just added it and I'm still writing the docs.

**Comment by ThePhD** [comment] 2016-03-03 08:16
If you mean that we should be catching ALL errors, including ones that we can't catch with `const char*`, `sol::error` or `std::exception`, then the answer there is going to have to be "we shouldn't", but even in that case for the c-function trampolines we do anyways. If luajit is directly throwing something as it executes the script and not properly calling atpanic, there's very little we can do to reconcile that.

**Comment by Nava2** [comment] 2016-03-03 15:01
So this was fixed in the latest edition? That's awesome, let me try it out for myself.

I wasn't sure if it was something you were investigating with your recent changes to exceptions.

**Comment by ThePhD** [comment] 2016-03-03 16:13
I'm going to assume this is fixed and closed it now. If something else goes entirely derelict, re-open it ASAP and I'll get on it (maybe even get a few Vagrant files to spin things up).

**Comment by Nava2** [comment] 2016-03-03 16:28
I actually can't verify that it's working. :-1:

```c++
sol::state lua;
                // should error
                // REQUIRE_THROWS_AS(lua.script(script), sol::error);
                try 
                {
                    lua.script("local M = require(\"M\")\n"
                               "assert(M.foo() == \"foo\")\n");
                } catch (sol::error& e)
                {
                    std::cout << "caught sol::error: " << e.what() << std::endl;
                }
                catch (std::runtime_error& e)
                {
                    FAIL("caught std::runtime_error: " << e.what());
                }
                catch (std::exception& e)
                {
                    FAIL("caught std::exception: " << e.what());
                }
                catch (const char* e)
                {
                    FAIL("caught char*: " << e);
                }
                catch (...)
                {
                    try {
                        auto eptr = std::current_exception();
                        if (eptr)
                            std::rethrow_exception(eptr);
                        else 
                            FAIL("caught(...)");
                    } catch (std::exception& e)
                    {
                        FAIL("caught (...): " << e.what());
                    }
                }
```

It fails with `caught (...)` (no extra message).

SOL_LUA_VERSION=501

**Comment by Nava2** [comment] 2016-03-03 16:37
Yup, needs to be reopened: https://travis-ci.org/Nava2/sol2/jobs/113445378

**Comment by ThePhD** [comment] 2016-03-03 16:56
RIP, and it fails on a regular linux container too. I'm not really running a linux build, just using g++/clang++ on a Windows machine... buh. I'll have to install an actual 64-bit linux at some point.

**Comment by Nava2** [comment] 2016-03-03 16:58
I've been doing development against all three, but recently, since making this [Vagrantfile](https://gist.github.com/Nava2/b50a8bc34f6f06a2fabf), I've been using the `gcc49` machine more and more.

**Comment by ThePhD** [comment] 2016-03-04 02:40
So, this is a tad troubling, but I'm not sure what I can do about it.

I've wrapped _every_ function call in a trampoline, and even `protected_function` features additional exception catching guarantees to ensure that `luajit` doesn't behave like this. The problem is, however, there's no way for me to force luajit to play nice: even after by-default assigning an exception-trapping handler using luajit's API and throwing through the `panic` function, luajit just doesn't rightly care on certain platforms (like Windows x86 and friends).

This is not something that's really within our control, unfortunately. Unless you can spot out any bright ideas, this seems like one of those "Well, it's your burden for using luajit."

**Comment by Nava2** [comment] 2016-03-04 03:16
Does the error reproduce on newer version so LuaJIT? I haven't tried, but I will now.

I fear it might come down to, as you said, "known problems." I'm surprised about this since the site does say that it should work as we expect on Linux. It's supposed to have [full interoperability](http://luajit.org/extensions.html#exceptions) with C++ exceptions on Linux.

**Comment by ThePhD** [comment] 2016-03-04 03:27
I'm using 2.0.4, which last I checked is the latest.

**Comment by Nava2** [comment] 2016-03-04 03:31
Yeah, I just verified as well. I'm not sure what to say about that. It stinks, but it is definitely able to be written around.

**Comment by ThePhD** [comment] 2016-03-04 03:32
Guess we just file bugs in `luajit` and pray for the best?

**Comment by Nava2** [comment] 2016-03-04 03:52
I think it's more of a "report to mailing list," but yeah. I think there needs to be a test case created *without sol* first, though.

**Comment by ThePhD** [comment] 2016-03-05 00:56
Unfortunately, we'll have to close this. :( I'll be sure to throw over a issue on the LuaJit Github, which is apparently the active place of development.

**Closed by ThePhD** 2016-03-05 00:56 UTC

**Comment by Nava2** [comment] 2016-03-05 04:46
Sounds good to me.. unfortunately. Where is the repository?

**Comment by drbo** [comment] 2016-03-28 04:08
One solution is to have exception-throwing C++ functions wrapped in functions that store `std::current_exception()` in a userdata and throw it as a Lua error, which the Sol API special-cases.

**Comment by drbo** [comment] 2016-03-28 04:11
The reason LuaJIT has issues is that, unlike PUC-Lua, LuaJIT is not written in the common subset of C and C++, but rather in C + assembler.  LuaJIT must therefore handle unwinding manually, hence the lack of portability.

**Comment by ThePhD** [comment] 2016-03-28 04:42
There's nothing we can do about this. If we turn off exceptions for LuaJIT and then it hits itsown error and calls atpanic and the atpanic throws, LuaJIT will not respect the thrown error on most platforms. If we simply return the error message or the exception in a userdata, it doesn't matter because LuaJIT -- like vanilla Lua -- will call `abort` once the atpanic function finishes and the user does not `lngjmp` or `throw` their way out of it.

I am not interested in re-inventing exceptions with some weird longjmp bullshit because LuaJIT does not keep its promises on 64-bit Linux.

**Comment by espkk** [comment] 2018-07-22 13:39
@ThePhD 
Thank you for your quick reply. I read both LuaJIT and sol documentation, but I had a hope that I misunderstood.

**Comment by ThePhD** [comment] 2018-07-22 13:43
For what it's worth, you can define `SOL_NO_EXCEPTIONS 1` and just let your exceptions tear through the stack without any interference from sol. If it works out, well, have fun.

**Comment by espkk** [comment] 2018-07-22 14:36
@ThePhD 
Seems to be solved by setting `LJ_UNWIND_EXT` to 0, but thanks for the help anyway
