### ISSUE TITLE
VS2017 & VS2015 aligned member variable C2718 error

### ISSUE THREAD

**Issue by igorkrpanic** [ThePhD/sol2#487] opened 2017-08-17 19:43 UTC
When I try to wrap class with aligned member variable I get C2718 error. The following sample can reproduce it.

```cpp
#include <sol/sol.hpp>

__declspec(align(16)) class aligned_class
{
    int var;
};

class A
{
    aligned_class a;
};

int main()
{
    sol::state lua;
    lua.open_libraries( sol::lib::base, sol::lib::math );

    lua.new_usertype<A>( "A" );
}
```

Compiling will produce this error:
```
1>main.cpp
1>c:\devel\sol2\single\sol\sol.hpp(1234): error C2718: 'A': actual parameter with requested alignment of 16 won't be aligned
1>c:\devel\sol2\single\sol\sol.hpp(14309): note: see reference to alias template instantiation 'supports_op_less<A,A>' being compiled
1>c:\devel\sol2\single\sol\sol.hpp(14306): note: while compiling class template member function 'int sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs(std::array<luaL_Reg,32> &,int &)'
1>        with
1>        [
1>            T=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(14578): note: see reference to function template instantiation 'int sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs(std::array<luaL_Reg,32> &,int &)' being compiled
1>        with
1>        [
1>            T=A
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\type_traits(416): note: see reference to class template instantiation 'sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &>' being compiled
1>        with
1>        [
1>            T=A
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\memory(1761): note: see reference to class template instantiation 'std::is_convertible<sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &> *,sol::usertype_detail::registrar *>' being compiled
1>        with
1>        [
1>            T=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15274): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&,const char(&)[5],const sol::destructor_wrapper<void>&>(sol::usertype_detail::verified_tag,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15274): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&,const char(&)[5],const sol::destructor_wrapper<void>&>(sol::usertype_detail::verified_tag,const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15277): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&>(sol::usertype_detail::add_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<>> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15277): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&>(sol::usertype_detail::add_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<>> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15285): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&>(sol::usertype_detail::check_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<>> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15285): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<>>&>(sol::usertype_detail::check_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<>> &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15282): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<,sol::types<>>(sol::constructor_list<sol::types<>>)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15282): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<,sol::types<>>(sol::constructor_list<sol::types<>>)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15677): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<>(void)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(15677): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<>(void)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(16713): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::new_usertype<Class,>(const std::string &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2\single\sol\sol.hpp(16713): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::new_usertype<Class,>(const std::string &)' being compiled
1>        with
1>        [
1>            Class=A
1>        ]
1>c:\devel\sol2test\sol2test\main.cpp(272): note: see reference to function template instantiation 'sol::state_view &sol::state_view::new_usertype<A,>(const std::string &)' being compiled
1>c:\devel\sol2\single\sol\sol.hpp(1238): error C2718: 'A': actual parameter with requested alignment of 16 won't be aligned
1>c:\devel\sol2\single\sol\sol.hpp(14313): note: see reference to alias template instantiation 'supports_op_less_equal<A,A>' being compiled
1>c:\devel\sol2\single\sol\sol.hpp(1236): error C2718: 'A': actual parameter with requested alignment of 16 won't be aligned
1>c:\devel\sol2\single\sol\sol.hpp(14317): note: see reference to alias template instantiation 'supports_op_equal<A,A>' being compiled
1>c:\devel\sol2\single\sol\sol.hpp(1240): error C2718: 'A': actual parameter with requested alignment of 16 won't be aligned
1>c:\devel\sol2\single\sol\sol.hpp(14328): note: see reference to alias template instantiation 'supports_ostream_op<A,std::ostream>' being compiled
1>Done building project "sol2test.vcxproj" -- FAILED.
```

**Comment by ThePhD** [comment] 2017-08-18 09:42
No repro on VS 2017, x64 builds. Do you have any other setup / compiler information for me?

**Comment by IgorKrpanic** [comment] 2017-08-18 09:51
You are correct. I forgot to check x64.
x64 works, but x86 build produce the error.

**Comment by ThePhD** [comment] 2017-08-18 14:38
Mmn. So Microsoft is making me sweat here:

````
template <typename T, typename OS, typename = decltype(std::declval<OS&>() << std::declval<T&>())>
std::true_type supports_ostream_op(const T&, const OS&);
std::false_type supports_ostream_op(...);
````

Friendly neighborhood SFINAE code. Here's the problem: when it doesn't have the supported operator, it triggers the `...` (va_args) overload. The `va_args` overload. This overload does not properly handle the aligned specifier, and causes the issue. Repro:

````
__declspec(align(16)) class aligned_class {
	int var;
};

class A {
	aligned_class a;
};

struct value_t {
	aligned_class var;

	value_t() {
		std::cout << "created" << std::endl;
	}

	value_t(const value_t&) {
		std::cout << "copied" << std::endl;
	}

	value_t& operator= (const value_t&) {
		std::cout << "copied" << std::endl;
		return *this;
	}

	~value_t() {
		std::cout << "destroyed" << std::endl;
	}
};

void test_it(const value_t&, const value_t&) {}

// causes compiler errors
//void test_it(...) {}

int main() {
	const value_t a{};
	test_it(a, a);
}
````

What's the fix? I have no goddamn clue. We'd have to change how we do SFINAE for every single type... but the PROBLEM is VS 2015 barely recognizes SFINAE as it is, and this is one of the only ways to play nice with the compiler at all. I honestly don't know how to go about fixing this properly.

**Comment by IgorKrpanic** [comment] 2017-08-18 17:59
pass by value is the problem. If called by ref `test_it(std::ref(a), std::ref(a))` it compiles.

I tried `std::ref` wrap in sol headers and it compiles and looks like it might be working ok but at this point I am not sure I know what I am doing :)
I will have to do more testing. Here is my changes to sol header:
```cpp
template <typename T, typename U = T>
using supports_op_less = decltype(meta_detail::supports_op_less_test(std::ref(std::declval<T&>()), std::ref(std::declval<U&>())));
template <typename T, typename U = T>
using supports_op_equal = decltype(meta_detail::supports_op_equal_test(std::ref(std::declval<T&>()), std::ref(std::declval<U&>())));
template <typename T, typename U = T>
using supports_op_less_equal = decltype(meta_detail::supports_op_less_equal_test(std::ref(std::declval<T&>()), std::ref(std::declval<U&>())));
template <typename T, typename U = std::ostream>
using supports_ostream_op = decltype(meta_detail::supports_ostream_op(std::ref(std::declval<T&>()), std::ref(std::declval<U&>())));
```

**Comment by igorkrpanic** [comment] 2017-08-19 10:02
I ran gcc 7.1 linux build with those changes since it was simpler to run the tests and it failed at two test cases regarding operator==. I have not tried it windows build.
But there is a new twist... today I got notified of new VS20117 update which I installed and align(16) now compiles. In fact anything up to 128 compiles. 128 produces the same error. x64 build also breaks at 128.

**Comment by ThePhD** [comment] 2017-08-19 10:08
I would imagine VS 2017's latest version fails at 128 because storing something with an alignment larger than that -- despite the `align` keyword stating that it can go up by power of 2's to something like 4096 -- begins to spill over some of the largest SIMD registers you can find out in the wild to date. Last I checked, 128 was the widest possible, and anything larger has no true reason for alignment anyhow, right?

**Comment by igorkrpanic** [comment] 2017-08-19 11:14
I have built my original code base and with freshly updated compiler compiles just fine. I am migrating large code base from luabind to sol2 and it will take me some time to get to the testable executable but for now it is looking good. Original problem appeared when wrapping class which were using Bullet3 types that has to be aligned for SIMD instructions.
So I would say this is fixed by compiler update, at least for VS2017. VS2015 still has issues but it is not a problem from me.
Thank you for your effort.

**Comment by OrfeasZ** [comment] 2017-08-20 05:38
I just happened to encounter this issue too. In my case, it was because a class I was binding via Sol2 had a member that was 16-byte aligned (and therefore inherited that alignment). I worked around that by changing that member to a pointer (was a value type) and doing the necessary aligned allocations/deallocations in the constructor and destructor of my class.

**Comment by ThePhD** [comment] 2017-08-21 19:43
I managed to put a fix for this into the latest that does not error with GCC. This should protect against most classes of errors from VC++ and leave GCC untouched by the taint of the fix. This fix should also only be active on `_MSC_VER <= 1900`, which should not include the updated compiler I THINK. If it does, well... it should still work there too.

Thanks for reporting, and best of luck! If you do anything fun with sol2, do come back and let me know about it.

**Closed by ThePhD** 2017-08-21 19:43 UTC
Labels: Bug.ExternalCan'tFix, Bug.WellShit, Maybe.Bug...?, Speed.Purrformance
